name: Platform Build

on:  
  pull_request:
    types: 
      - opened
      - synchronize
      - reopened
    branches:
      - main
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  default:    
    uses: ./.github/workflows/godot_template.yml
    # Using a strategey matrix like this will allow us to simply specify the configuration for future build targets without having to rewrite them
    strategy:
      matrix:
        include:
          - target: "Windows Desktop"
            output_path: Sick_Day_Delivery_win.exe
          - target: "Linux/X11"
            output_path: Sick_Day_Delivery_linux.x86_64
    with: 
      target_name: ${{ matrix.target }}
      output_path: ${{ matrix.output_path }}
    secrets: inherit
